[build]
  command = "yarn build"
  functions = "functions-build"
  publish = "build"

# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [context.production.environment]
    REACT_APP_CHAIN_ID = "3"

[context.bnbtest]
  [context.bnbtest.environment]
    REACT_APP_CHAIN_ID = "97"